todo_project/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

import views

router = DefaultRouter()
router.register(r'lists', views.TodoListViewSet, base_name='lists')
router.register(r'todo', views.TodoViewSet, base_name='todo')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

todo_project/loginsys/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/', views.RegisterFormView.as_view(), name='register'),
    url(r'^login/', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/', views.LogoutView.as_view(), name='logout'),

]

todo_project/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^todo/', include('todo.urls', namespace="todo")),
    url(r'^loginsys/', include('loginsys.urls', namespace="loginsys")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^', include('main.urls', namespace="main")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

todo_project/templates/basic.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% load staticfiles %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/favicon.png" type="image/x-icon">
    <title>Todo</title>
    <link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}"/>
</head>
<div class="block_header" align="right">
    {#    <a role="button" href="{% url 'todo:home' %}" class="btn btn-default" aria-label="Left Align">#}
    {#        <span class="glyphicon glyphicon-home"></span> Home</a>#}
    {% if user.is_authenticated %}
        <a role="button" href="{% url 'loginsys:logout' %}" class="btn btn-default" aria-label="Left Align">Logout
            <em>{{ user.username }}</em></a>
    {% else %}
        <a role="button" href="{% url 'loginsys:login' %}" class="btn btn-default" aria-label="Left Align">
            <span class="glyphicon glyphicon-log-in"></span> Log in</a>
        <a role="button" href="{% url 'loginsys:register' %}" class="btn btn-info" aria-label="Left Align">
            Registration</a>
    {% endif %}
</div>
<body>
<div class="block_main">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>