todo_project/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

import views

router = DefaultRouter()
router.register(r'lists', views.TodoListViewSet, base_name='lists')
router.register(r'todo', views.TodoViewSet, base_name='todo')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

todo_project/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^todo/', include('todo.urls', namespace="todo")),
    url(r'^loginsys/', include('loginsys.urls', namespace="loginsys")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^', include('main.urls', namespace="main")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

todo_project/todo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.TodoListView.as_view(), name='todo_list'),
    url(r'^create_list$', views.TodoListCreateView.as_view(), name='create_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.TodosView.as_view(), name='todos'),
    url(r'^(?P<pk>[0-9]+)/remove/$', views.RemoveTodoListView.as_view(), name='remove_list'),
    url(r'^(?P<pk>[0-9]+)/rename_list/$', views.RenameTodoListView.as_view(), name='rename_todo_list'),

    url(r'^(?P<list_pk>[0-9]+)/create_todo/$', views.CreateTodoView.as_view(), name='create_todo'),
    url(r'^(?P<todolist_pk>[0-9]+)/(?P<pk>[0-9]+)/remove_todo/$', views.RemoveTodoView.as_view(), name='remove_todo'),
    url(r'^(?P<todolist_pk>[0-9]+)/(?P<pk>[0-9]+)/edit/$', views.EditTodoView.as_view(), name='edit_todo'),
    url(r'^(?P<todolist_pk>[0-9]+)/(?P<pk>[0-9]+)/$', views.TodoDetailView.as_view(), name='todo_detail'),

]

todo_project/todo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


class TodoList(models.Model):
    """Model for storing a list of names and dates of creation"""

    name_of_list = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __unicode__(self):
        return self.name_of_list

    def count_tasks(self):
        return self.todo_set.count()

    def get_absolute_url(self):
        return reverse('todo:todos', kwargs={'pk': self.id})


class Todo(models.Model):
    """Model for the storage of information on the todo"""

    todo_list = models.ForeignKey(TodoList)
    name_of_todo = models.CharField(max_length=101)
    pub_date = models.DateTimeField(auto_now_add=True)
    task = models.TextField(help_text='Description of the problem')
    status = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name_of_todo

    def get_absolute_url(self):
        return reverse('todo:todo_detail', kwargs={'todolist_pk': self.todo_list.id, 'pk': self.id})

todo_project/todo/forms.py
"""
Preparation for the future functional
"""

todo_project/todo/views.py
from django.views.generic import ListView, DetailView, DeleteView, UpdateView
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import Todo, TodoList


class TodoListView(ListView):  # correct
    """Displays all the lists"""

    model = TodoList
    template_name = 'todo/todo_lists.html'
    context_object_name = 'todolist'

    def get_queryset(self):
        user = self.request.user
        if self.request.user.is_authenticated():
            lists = TodoList.objects.filter(owner=user)
            return lists


class TodoListCreateView(CreateView):  # correct
    """Create a list"""

    model = TodoList
    template_name = 'todo/create_list.html'
    fields = ['name_of_list']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(TodoListCreateView, self).form_valid(form)


class RenameTodoListView(UpdateView):  # correct
    """Renames the current list"""

    model = TodoList
    template_name = 'todo/rename_list.html'
    fields = ['name_of_list', ]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(RenameTodoListView, self).form_valid(form)


class RemoveTodoListView(DeleteView):  # correct
    """Deletes the current list"""

    model = TodoList
    template_name = 'todo/remove_list.html'
    success_url = reverse_lazy('todo:todo_list')


class TodosView(DetailView):  # correct
    """Displays all tasks"""

    model = TodoList
    template_name = 'todo/todos.html'


class CreateTodoView(CreateView):  # correct
    """Create a task"""

    model = Todo
    template_name = 'todo/create_todo.html'
    fields = ['name_of_todo', 'task']
    todo_list = None

    def get_todo_list(self):
        list_pk = self.kwargs.get('list_pk', None)
        self.todo_list = get_object_or_404(TodoList, pk=list_pk)

    def get_context_data(self, **kwargs):
        self.get_todo_list()
        context = super(CreateTodoView, self).get_context_data(**kwargs)
        context['todo_list'] = self.todo_list
        return context

    def form_valid(self, form):
        self.get_todo_list()
        form.instance.todo_list = self.todo_list
        return super(CreateTodoView, self).form_valid(form)


class EditTodoView(UpdateView):  # correct
    """Edits the current task"""

    model = Todo
    template_name = 'todo/edit_todo.html'
    fields = ['task', 'status']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(EditTodoView, self).form_valid(form)


class RemoveTodoView(DeleteView):  # correct
    """Removes the current task"""

    model = Todo
    template_name = 'todo/remove_todo.html'
    success_url = reverse_lazy('todo:todo_list')


class TodoDetailView(DetailView):  # correct
    """Detailed view of the current task"""

    model = Todo
    template_name = 'todo/todo_detail.html'

    # def form_valid(self, form):
    #     form.instance.owner = self.request.user
    #     return super(TodoDetailView, self).form_valid(form)

todo_project/todo/templates/todo/create_list.html
{% extends "basic.html" %}
{% block content %}
    {% load bootstrap3 %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
        <div align="right" class="block_navigation">
            <ol class="breadcrumb">
                <li><a href="{% url 'todo:todo_list' %}"><span class="nav_text">Your lists</span></a></li>
                <li class="active"><span class="nav_text">Create a list</span></li>
            </ol>
        </div>

        <h1>Create a new list</h1>
        <hr width="30%">
        <p></p>

        <div class="block1" align="center">

        {% if form.errors %}
            <div class="alert alert-danger">
                <p>Unable to create a new todo list. Please, fix errors listed below.</p>
            </div>
        {% endif %}

        <form method="post" action="">

        {% bootstrap_form form %}
        {% csrf_token %}
        <a role="button" href="{% url 'todo:todo_list' %}" class="btn btn-default">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
        </a>
        <button type="submit" class="btn btn-primary" aria-label="Left Align">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create
        </button>
    {% else %}
        <span class="warning_text">You are not authorized. Access is denied.</span>
    {% endif %}
</form>
</div>
</div>
{% endblock content %}

todo_project/todo/templates/todo/create_todo.html
{% extends "basic.html" %}
{% block content %}
    {% load bootstrap3 %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
            <div align="right" class="block_navigation">
                <ol class="breadcrumb">
                    <li><a href="{% url 'todo:todo_list' %}"><span class="nav_text">Your lists</span></a></li>
                    <li class="active"><span class="nav_text">Create a todo</span></li>
                </ol>
            </div>
        </div>

        <h1>Create a new todo</h1>
        <hr width="30%">
        <div class="block1" align="center">

        {% if form.errors %}
            <div class="alert alert-danger">
                <p>Unable to create a new todo. Please, fix errors listed below.</p>
            </div>
        {% endif %}

        <form method="post" action="">

        {% bootstrap_form form %}
        {% csrf_token %}
        <a role="button" href="{% url 'todo:todos' todo_list.id %}" class="btn btn-default">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
        </a>
        <button type="submit" class="btn btn-primary" aria-label="Left Align">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create
        </button>
    {% else %}
        <span class="warning_text">You are not authorized. Access is denied.</span>
    {% endif %}
</form>

</div>
{% endblock content %}

todo_project/todo/templates/todo/edit_todo.html
{% extends "basic.html" %}
{% block content %}
    {% load bootstrap3 %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
        <div align="right" class="block_navigation">
            <ol class="breadcrumb">
                <li><a href="{% url 'todo:todo_list' %}"><span class="nav_text">Your lists</span></a></li>
                <li><span class="nav_text">{{ object.todo_list }}</span></li>
                <li><span class="nav_text">{{ object.name_of_todo }}</span></li>
                <li class="active"><span class="nav_text">Edit task</span></li>
            </ol>
        </div>
        <h1>Edit task</h1>
    {% endif %}
<hr width="30%">
<div class="block1" align="center">

    {% if form.errors %}
        <div class="alert alert-danger">
            <p>Unable to add new task. Please, fix errors listed below.</p>
        </div>
    {% endif %}

    <form method="post" action="">
        {% if user.is_authenticated %}
            {% bootstrap_form form %}
            {% csrf_token %}
            <a role="button" href="{% url 'todo:todo_detail' object.todo_list.id object.id %}"
               class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
            </a>
            <button type="submit" class="btn btn-success" aria-label="Left Align">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Edit
            </button>
        {% else %}
            <span class="warning_text">You are not authorized. Access is denied.</span>
        {% endif %}
    </form>

</div>
</div>
{% endblock content %}

todo_project/todo/templates/todo/remove_list.html
{% extends "basic.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
            <div align="right" class="block_navigation">
                <ol class="breadcrumb">
                    <li><span class="nav_text">Your lists</span></li>
                    <li><span class="nav_text">{{ object.name_of_list }}</span></li>
                    <li class="active"><span class="nav_text">Delete a list</span></li>
                </ol>
            </div>
        </div>
        <h1>Are you sure you want to delete {{ object.name_of_list }} list?</h1>
        <hr width="30%">
        <form action="" method="post">
        {% csrf_token %}
        <div class="row" align="center">

            <button type="submit" class="btn btn-success" aria-label="Left Align">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Yes
            </button>
            <a role="button" href="{% url 'todo:todos' object.id %}" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> No
            </a>

        </div>
    {% else %}
        <span class="warning_text">You are not authorized. Access is denied.</span>
    {% endif %}
</form>
{% endblock content %}

todo_project/todo/templates/todo/remove_todo.html
{% extends "basic.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
            <div align="right" class="block_navigation">
                <ol class="breadcrumb">
                    <li class="active"><span class="nav_text">Your lists</span></li>
                    <li class="active"><span class="nav_text">{{ object.todo_list }}</span></li>
                    <li class="active"><span class="nav_text">{{ object.name_of_todo }}</span></li>
                    <li class="active"><span class="nav_text">Delete a todo</span></li>
                </ol>
            </div>
        </div>
        <h1>Are you sure you want to delete {{ object.name_of_todo }} todo?</h1>
        <hr width="30%">
        <form action="" method="post">
        {% csrf_token %}

        <div class="row" align="center">
            <button type="submit" class="btn btn-success" aria-label="Left Align">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Yes
            </button>
            <a role="button" href="{% url 'todo:todo_detail' object.todo_list.id object.id %}"
               class="btn btn-danger">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> No
            </a>

        </div>
    {% else %}
        <span class="warning_text">You are not authorized. Access is denied.</span>
    {% endif %}
</form>
{% endblock content %}

todo_project/todo/templates/todo/rename_list.html
{% extends "basic.html" %}
{% load bootstrap3 %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
        <div align="right" class="block_navigation">
            <ol class="breadcrumb">
                <li><a href="{% url 'todo:todo_list' %}"><span class="nav_text">Your lists</span></a></li>
                <li><span class="nav_text">{{ object.name_of_list }}</span></li>
                <li class="active"><span class="nav_text">Rename a list</span></li>
            </ol>
        </div>
        <h1>Rename list</h1>
        <hr width="30%">
        <div class="block1" align="center">

        {% if form.errors %}
            <div class="alert alert-danger">
                <p>Unable to add new task. Please, fix errors listed below.</p>
            </div>
        {% endif %}

        <form method="post" action="">

        {% bootstrap_form form %}
        {% csrf_token %}
        <a role="button" href="{% url 'todo:todos' object.id %}" class="btn btn-default">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
        </a>
        <button type="submit" class="btn btn-success" aria-label="Left Align">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Rename
        </button>
    {% else %}
        <span class="warning_text">You are not authorized. Access is denied.</span>
    {% endif %}
</form>

</div>
</div>
{% endblock content %}

todo_project/todo/templates/todo/todo_detail.html
{% extends "basic.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
        <div align="right" class="block_navigation">
            <ol class="breadcrumb">
                <li><a href="{% url 'todo:todo_list' %}"><span class="nav_text">Your lists</span></a></li>
                <li><span class="nav_text">{{ object.todo_list }}</span></li>
                <li class="active"><span class="nav_text">{{ object.name_of_todo }}</span></li>
            </ol>
        </div>
        <h1>{{ object.name_of_todo }}:</h1>
        <hr width="30%">
        <div class="table_conf" align="center">
            {% if object %}
                <table class="table table-bordered">
                    <tr class="warning">
                        <th><p class="text-center">Task</p></th>
                        <th><p class="text-center">Status</p></th>
                        <th><p class="text-center">Date</p></th>
                    </tr>
                    <tr>
                        <td align="center">{{ object.task }}</td>
                        <td align="center">
                            {% if  object.status == True %}
                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                            {% else %}
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            {% endif %}
                        </td>
                        <td align="center"><p>{{ object.pub_date }}</p></td>
                    </tr>
                </table>
            {% else %}
                <p>No tasks in your todo</p>
            {% endif %}
        </div>
        <p></p>

        <div class="block_button" align="center">
            <a role="button" href="{% url 'todo:todos' object.todo_list.id %}" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
            </a>

            <a type="button" href="{% url 'todo:edit_todo' todolist_pk=object.todo_list.id pk=object.id %}"
               class="btn btn-success" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
            </a>

            <a type="button" href="{% url 'todo:remove_todo' object.todo_list.id object.id %}"
               class="btn btn-danger">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Todo
            </a>
        </div>
    {% else %}
        <div align="center">
            <span class="warning_text">You are not authorized. Access is denied.</span>
        </div>
    {% endif %}
</div>
{% endblock content %}

todo_project/todo/templates/todo/todo_lists.html
{% extends "basic.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
            <div align="right" class="block_navigation">
                <ol class="breadcrumb">
                    <li class="active"><span class="nav_text">Your lists</span></li>
                </ol>
            </div>
        </div>
        <h1>Your Lists:</h1>
        <hr width="30%">

        {% if user.username and todolist.count %}
            <div class="table_conf" align="center">
            <table class="table table-bordered">
                <tr class="warning">
                    <th><p class="text-center">Title List</p></th>
                    <th><p class="text-center">Date</p></th>
                    <th><p class="text-center">Number of todo</p></th>
                </tr>

                {% for name in todolist %}
                    <tr>
                        <td align="center"><a href="{% url 'todo:todos' name.id %}">{{ name.name_of_list }}</a></td>
                        <td align="center">{{ name.pub_date }}</td>
                        <td align="center"><span class="badge">{{ name.count_tasks }}</span></td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <span class="warning_text">No list are available</span>
        {% endif %}
    </div>

        <div class="block_button" align="center">
            <a role="button" href="{% url 'todo:create_list' %}" class="btn btn-primary" aria-label="Left Align">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create a list
            </a>
        </div>
    {% else %}
        <div align="center">
            <span class="warning_text">You are not authorized. Access is denied.</span>
        </div>
    {% endif %}
{% endblock content %}

todo_project/todo/templates/todo/todos.html
{% extends "basic.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="col" align="right">
            <div align="right" class="block_navigation">
                <ol class="breadcrumb">
                    <li><a href="{% url 'todo:todo_list' %}"><span class="nav_text">Your lists</span></a></li>
                    <li class="active"><span class="nav_text">{{ object.name_of_list }}</span></li>
                </ol>
            </div>
        </div>
        <h1>List {{ object.name_of_list }}: </h1>
        <hr width="30%">
        {% if object.todo_set.all %}
            <div class="table_conf" align="center">
            <table class="table table-bordered">
                <tr class="warning">
                    <th><p class="text-center">Name</p></th>
                    <th><p class="text-center">Task</p></th>
                    <th><p class="text-center">Status</p></th>
                    <th><p class="text-center">Date</p></th>
                </tr>
                {% for name in object.todo_set.all %}
                    <tr>
                        <td align="center"><a
                                href="{% url 'todo:todo_detail' object.id name.id %}">{{ name.name_of_todo }}</a></td>
                        <td align="center">{{ name.task }}</td>
                        <td align="center">{% if  name.status == True %}
                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        {% else %}
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        {% endif %}</td>
                        <td align="center">{{ name.pub_date }}</td>
                    </tr>
                {% endfor %}
            </table>

        {% else %}
            <span class="warning_text">In your list any tasks. Create a task using a button - "Create Todo"</span>

        {% endif %}

    </div>

        <div class="row" align="center">
            <a role="button" href="{% url 'todo:todo_list' %}" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
            </a>

            <a type="button" href="{% url 'todo:create_todo' list_pk=object.id %}" class="btn btn-success"
               aria-label="Left Align">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create Todo
            </a>

            <a role="button" href="{% url 'todo:rename_todo_list' object.id %}" class="btn btn-primary">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Rename {{ object.name_of_list }}
            </a>

            <a role="button" href="{% url 'todo:remove_list' object.id %}" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete {{ object.name_of_list }}
            </a>
        </div>
    {% else %}
        <div align="center">
            <span class="warning_text">You are not authorized. Access is denied.</span>
        </div>
    {% endif %}
{% endblock content %}